[2025-03-31T01:14:20.758+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model.train_model manual__2025-03-31T01:14:16.168989+00:00 [queued]>
[2025-03-31T01:14:20.782+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model.train_model manual__2025-03-31T01:14:16.168989+00:00 [queued]>
[2025-03-31T01:14:20.783+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-31T01:14:20.818+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_model> on 2025-03-31 01:14:16.168989+00:00
[2025-03-31T01:14:20.845+0000] {standard_task_runner.py:57} INFO - Started process 1475 to run task
[2025-03-31T01:14:20.854+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'train_model', 'train_model', 'manual__2025-03-31T01:14:16.168989+00:00', '--job-id', '546', '--raw', '--subdir', 'DAGS_FOLDER/train.py', '--cfg-path', '/tmp/tmpc2n8p0io']
[2025-03-31T01:14:20.861+0000] {standard_task_runner.py:85} INFO - Job 546: Subtask train_model
[2025-03-31T01:14:21.008+0000] {task_command.py:410} INFO - Running <TaskInstance: train_model.train_model manual__2025-03-31T01:14:16.168989+00:00 [running]> on host 76e1807f7118
[2025-03-31T01:14:21.190+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_model' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T01:14:16.168989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T01:14:16.168989+00:00'
[2025-03-31T01:14:21.216+0000] {base.py:73} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-03-31T01:14:21.354+0000] {logging_mixin.py:149} INFO - Experiment 'mlflow_tracking_examples_3' already exists with ID: 1
[2025-03-31T01:14:21.397+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:736: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2025-03-31T01:14:21.401+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  UserWarning,

[2025-03-31T01:14:21.982+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train.py", line 96, in train_model
    client.set_tag("column_names", ",".join(columns))
TypeError: set_tag() missing 1 required positional argument: 'value'
[2025-03-31T01:14:22.008+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model, task_id=train_model, execution_date=20250331T011416, start_date=20250331T011420, end_date=20250331T011422
[2025-03-31T01:14:22.034+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 546 for task train_model (set_tag() missing 1 required positional argument: 'value'; 1475)
[2025-03-31T01:14:22.111+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-31T01:14:22.158+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
