[2025-04-05T19:51:04.445+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T19:51:04.478+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-05T19:50:59.269042+00:00 [queued]>
[2025-04-05T19:51:04.493+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-05T19:50:59.269042+00:00 [queued]>
[2025-04-05T19:51:04.493+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-05T19:51:04.517+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2025-04-05 19:50:59.269042+00:00
[2025-04-05T19:51:04.539+0000] {standard_task_runner.py:63} INFO - Started process 89863 to run task
[2025-04-05T19:51:04.555+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clean_transform_data', 'transform_data', 'manual__2025-04-05T19:50:59.269042+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpo0pye3ld']
[2025-04-05T19:51:04.565+0000] {standard_task_runner.py:91} INFO - Job 659: Subtask transform_data
[2025-04-05T19:51:04.657+0000] {task_command.py:426} INFO - Running <TaskInstance: clean_transform_data.transform_data manual__2025-04-05T19:50:59.269042+00:00 [running]> on host 1e5dd8b23497
[2025-04-05T19:51:04.807+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_transform_data' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T19:50:59.269042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T19:50:59.269042+00:00'
[2025-04-05T19:51:04.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T19:51:04.845+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-05T19:51:04.857+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-05T19:51:04.903+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-04-05T19:51:12.676+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T19:51:12.678+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T19:51:12.689+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clean_transform_data, task_id=transform_data, execution_date=20250405T195059, start_date=20250405T195104, end_date=20250405T195112
[2025-04-05T19:51:12.774+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T19:51:12.795+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T19:51:12.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
