[2025-05-03T06:55:51.148+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T06:55:51.220+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_data_pipeline.preprocess_validation_data manual__2025-05-03T06:54:45.866028+00:00 [queued]>
[2025-05-03T06:55:51.265+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_data_pipeline.preprocess_validation_data manual__2025-05-03T06:54:45.866028+00:00 [queued]>
[2025-05-03T06:55:51.265+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T06:55:51.370+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): preprocess_validation_data> on 2025-05-03 06:54:45.866028+00:00
[2025-05-03T06:55:51.404+0000] {standard_task_runner.py:63} INFO - Started process 482 to run task
[2025-05-03T06:55:51.438+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_data_pipeline', 'preprocess_validation_data', 'manual__2025-05-03T06:54:45.866028+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/process_and_clean_data.py', '--cfg-path', '/tmp/tmptyr5ylgn']
[2025-05-03T06:55:51.449+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask preprocess_validation_data
[2025-05-03T06:55:51.763+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_data_pipeline.preprocess_validation_data manual__2025-05-03T06:54:45.866028+00:00 [running]> on host e89618938543
[2025-05-03T06:55:52.273+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_validation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T06:54:45.866028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T06:54:45.866028+00:00'
[2025-05-03T06:55:52.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T06:55:55.960+0000] {process_and_clean_data.py:317} INFO - Iniciando preprocesamiento de datos validation...
[2025-05-03T06:55:56.161+0000] {warnings.py:109} WARNING - /opt/***/dags/process_and_clean_data.py:169: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diabetes_num['service_utilization'] = (df_diabetes_num['number_outpatient'] +

[2025-05-03T06:56:00.834+0000] {process_and_clean_data.py:382} INFO - âœ“ Datos validation preprocesados exitosamente:
[2025-05-03T06:56:00.838+0000] {process_and_clean_data.py:383} INFO -    - Filas: 20353
[2025-05-03T06:56:00.838+0000] {process_and_clean_data.py:384} INFO -    - Columnas: 84
[2025-05-03T06:56:00.964+0000] {python.py:237} INFO - Done. Returned value was:               0         1         2  ...  target  encounter_id  patient_nbr
0     -1.140016  0.296120  2.743213  ...      NO     132378714     93137184
1     -0.804981 -0.111382 -0.786066  ...      NO      79265022       934974
2     -0.469946 -1.741390  0.978573  ...      NO     146797440     88138098
3     -0.804981  1.213000 -0.786066  ...      NO      89524164     21539610
4     -1.140016 -1.282950 -0.786066  ...      NO      96010296     23807187
...         ...       ...       ...  ...     ...           ...          ...
20348 -1.140016 -0.366071  0.978573  ...      NO     173602944     71948700
20349  0.200125  0.347058 -0.197853  ...      NO     413765144     85683600
20350 -0.804981  0.245183  2.743213  ...      NO     178886514     23650902
20351 -1.140016 -0.366071 -0.786066  ...      NO     163655958     25327296
20352  0.200125  1.314876 -0.786066  ...     YES     277488072     91423089

[20353 rows x 84 columns]
[2025-05-03T06:56:01.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T06:56:01.836+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/serialization/serializers/pandas.py:49: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(o)

[2025-05-03T06:56:02.213+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=diabetes_data_pipeline, task_id=preprocess_validation_data, execution_date=20250503T065445, start_date=20250503T065551, end_date=20250503T065602
[2025-05-03T06:56:02.434+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-03T06:56:02.490+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T06:56:02.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
