[2025-05-03T07:04:06.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T07:04:06.286+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_data_pipeline.save_validation_data manual__2025-05-03T07:02:47.895663+00:00 [queued]>
[2025-05-03T07:04:06.310+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_data_pipeline.save_validation_data manual__2025-05-03T07:02:47.895663+00:00 [queued]>
[2025-05-03T07:04:06.313+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T07:04:06.378+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_validation_data> on 2025-05-03 07:02:47.895663+00:00
[2025-05-03T07:04:06.406+0000] {standard_task_runner.py:63} INFO - Started process 734 to run task
[2025-05-03T07:04:06.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_data_pipeline', 'save_validation_data', 'manual__2025-05-03T07:02:47.895663+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/process_and_clean_data.py', '--cfg-path', '/tmp/tmppc9xmlkr']
[2025-05-03T07:04:06.441+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask save_validation_data
[2025-05-03T07:04:06.673+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_data_pipeline.save_validation_data manual__2025-05-03T07:02:47.895663+00:00 [running]> on host e89618938543
[2025-05-03T07:04:07.165+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_data_pipeline' AIRFLOW_CTX_TASK_ID='save_validation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T07:02:47.895663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T07:02:47.895663+00:00'
[2025-05-03T07:04:07.169+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T07:04:10.515+0000] {process_and_clean_data.py:417} INFO - Guardando datos procesados en tabla diabetes_validation_processed...
[2025-05-03T07:04:10.576+0000] {process_and_clean_data.py:497} INFO - SQL de creaci√≥n de tabla: 
        CREATE TABLE IF NOT EXISTS diabetes_validation_processed (
            `feature_0` DOUBLE(15,8), `feature_1` DOUBLE(15,8), `feature_2` DOUBLE(15,8), `feature_3` DOUBLE(15,8), `feature_4` DOUBLE(15,8), `feature_5` DOUBLE(15,8), `feature_6` DOUBLE(15,8), `feature_7` DOUBLE(15,8), `feature_8` DOUBLE(15,8), `feature_9` INT, `feature_10` INT, `feature_11` INT, `feature_12` INT, `feature_13` INT, `feature_14` INT, `feature_15` INT, `feature_16` INT, `feature_17` INT, `feature_18` INT, `feature_19` INT, `feature_20` INT, `feature_21` INT, `feature_22` INT, `feature_23` INT, `feature_24` INT, `feature_25` INT, `feature_26` INT, `feature_27` INT, `feature_28` INT, `feature_29` INT, `feature_30` INT, `feature_31` INT, `feature_32` INT, `feature_33` INT, `feature_34` INT, `feature_35` INT, `feature_36` INT, `feature_37` INT, `feature_38` INT, `feature_39` INT, `feature_40` INT, `feature_41` INT, `feature_42` INT, `feature_43` INT, `feature_44` INT, `feature_45` INT, `feature_46` INT, `feature_47` INT, `feature_48` INT, `feature_49` INT, `feature_50` INT, `feature_51` INT, `feature_52` INT, `feature_53` INT, `feature_54` INT, `feature_55` INT, `feature_56` INT, `feature_57` INT, `feature_58` INT, `feature_59` INT, `feature_60` INT, `feature_61` INT, `feature_62` INT, `feature_63` INT, `feature_64` INT, `feature_65` INT, `feature_66` INT, `feature_67` INT, `feature_68` INT, `feature_69` INT, `feature_70` INT, `feature_71` INT, `feature_72` INT, `feature_73` INT, `feature_74` INT, `feature_75` INT, `feature_76` INT, `feature_77` INT, `feature_78` INT, `feature_79` INT, `feature_80` INT, `target` VARCHAR(255), `encounter_id` INT, `patient_nbr` INT
        )
        
[2025-05-03T07:04:10.583+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-03T07:04:10.585+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:10.597+0000] {sql.py:457} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS diabetes_validation_processed (
            `feature_0` DOUBLE(15,8), `feature_1` DOUBLE(15,8), `feature_2` DOUBLE(15,8), `feature_3` DOUBLE(15,8), `feature_4` DOUBLE(15,8), `feature_5` DOUBLE(15,8), `feature_6` DOUBLE(15,8), `feature_7` DOUBLE(15,8), `feature_8` DOUBLE(15,8), `feature_9` INT, `feature_10` INT, `feature_11` INT, `feature_12` INT, `feature_13` INT, `feature_14` INT, `feature_15` INT, `feature_16` INT, `feature_17` INT, `feature_18` INT, `feature_19` INT, `feature_20` INT, `feature_21` INT, `feature_22` INT, `feature_23` INT, `feature_24` INT, `feature_25` INT, `feature_26` INT, `feature_27` INT, `feature_28` INT, `feature_29` INT, `feature_30` INT, `feature_31` INT, `feature_32` INT, `feature_33` INT, `feature_34` INT, `feature_35` INT, `feature_36` INT, `feature_37` INT, `feature_38` INT, `feature_39` INT, `feature_40` INT, `feature_41` INT, `feature_42` INT, `feature_43` INT, `feature_44` INT, `feature_45` INT, `feature_46` INT, `feature_47` INT, `feature_48` INT, `feature_49` INT, `feature_50` INT, `feature_51` INT, `feature_52` INT, `feature_53` INT, `feature_54` INT, `feature_55` INT, `feature_56` INT, `feature_57` INT, `feature_58` INT, `feature_59` INT, `feature_60` INT, `feature_61` INT, `feature_62` INT, `feature_63` INT, `feature_64` INT, `feature_65` INT, `feature_66` INT, `feature_67` INT, `feature_68` INT, `feature_69` INT, `feature_70` INT, `feature_71` INT, `feature_72` INT, `feature_73` INT, `feature_74` INT, `feature_75` INT, `feature_76` INT, `feature_77` INT, `feature_78` INT, `feature_79` INT, `feature_80` INT, `target` VARCHAR(255), `encounter_id` INT, `patient_nbr` INT
        )
        , parameters: None
[2025-05-03T07:04:10.608+0000] {sql.py:466} INFO - Rows affected: 0
[2025-05-03T07:04:10.620+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:10.636+0000] {sql.py:457} INFO - Running statement: TRUNCATE TABLE diabetes_validation_processed, parameters: None
[2025-05-03T07:04:10.727+0000] {sql.py:466} INFO - Rows affected: 0
[2025-05-03T07:04:13.084+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.108+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 1: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.109+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.124+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 2: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.128+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.144+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 3: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.154+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.178+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 4: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.185+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.215+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 5: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.216+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.240+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 6: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.243+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.257+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 7: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.258+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.272+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 8: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.273+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.290+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 9: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.294+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.313+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 10: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.319+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.328+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 11: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.331+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.352+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 12: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.355+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.369+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 13: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.372+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.392+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 14: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.394+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.427+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 15: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.438+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.453+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 16: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.455+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.470+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 17: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.471+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.494+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 18: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.496+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.511+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 19: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.515+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.545+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 20: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.554+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.589+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 21: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.597+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.655+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 22: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.664+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.690+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 23: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.694+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.727+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 24: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.735+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.758+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 25: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.769+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.786+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 26: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.790+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.798+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 27: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.801+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.808+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 28: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.815+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.837+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 29: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.842+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.868+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 30: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.869+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.887+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 31: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.889+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.900+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 32: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.902+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.908+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 33: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.909+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.918+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 34: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.921+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.929+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 35: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.933+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:13.958+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 36: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:13.960+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.005+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 37: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.013+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.055+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 38: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.058+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.084+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 39: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.088+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.119+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 40: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.121+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.138+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 41: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.141+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.154+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 42: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.155+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.165+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 43: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.166+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.197+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 44: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.199+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.216+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 45: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.221+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.262+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 46: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.267+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.284+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 47: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.288+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.307+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 48: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.311+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.325+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 49: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.331+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.347+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 50: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.353+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.369+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 51: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.372+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.397+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 52: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.399+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.410+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 53: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.422+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.449+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 54: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.454+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.462+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 55: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.463+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.477+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 56: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.483+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.509+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 57: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.511+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.533+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 58: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.539+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.554+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 59: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.559+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.584+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 60: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.594+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.627+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 61: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.630+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.653+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 62: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.659+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.669+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 63: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.672+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.696+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 64: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.700+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.721+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 65: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.726+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.738+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 66: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.742+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.758+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 67: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.763+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.779+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 68: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.795+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.825+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 69: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.829+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.851+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 70: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.852+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.888+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 71: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.896+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.927+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 72: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.934+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.952+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 73: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.954+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:14.974+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 74: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:14.980+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.002+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 75: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.006+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.029+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 76: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.032+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.049+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 77: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.053+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.082+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 78: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.092+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.117+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 79: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.121+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.135+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 80: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.136+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.168+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 81: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.175+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.191+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 82: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.194+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.218+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 83: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.219+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.246+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 84: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.247+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.264+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 85: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.265+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.275+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 86: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.280+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.286+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 87: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.288+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.299+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 88: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.304+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.321+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 89: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.326+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.336+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 90: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.339+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.348+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 91: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.350+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.368+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 92: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.371+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.396+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 93: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.402+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.422+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 94: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.425+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.448+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 95: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.456+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.481+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 96: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.483+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.512+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 97: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.517+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.538+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 98: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.541+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.571+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 99: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.574+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.601+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 100: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.602+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.643+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 101: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.652+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.690+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 102: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.698+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.716+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 103: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.718+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.731+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 104: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.733+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.760+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 105: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.764+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.783+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 106: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.789+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.804+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 107: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.807+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.821+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 108: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.825+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.846+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 109: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.851+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.879+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 110: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.885+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.912+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 111: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.915+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:15.940+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 112: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:15.941+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.006+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 113: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.009+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.045+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 114: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.046+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.074+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 115: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.075+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.110+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 116: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.112+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.124+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 117: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.126+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.134+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 118: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.135+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.140+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 119: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.141+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.147+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 120: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.148+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.156+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 121: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.157+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.166+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 122: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.168+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.183+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 123: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.185+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.200+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 124: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.204+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.211+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 125: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.214+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.224+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 126: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.226+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.246+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 127: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.251+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.267+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 128: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.268+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.296+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 129: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.297+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.311+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 130: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.313+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.320+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 131: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.323+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.328+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 132: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.329+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.336+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 133: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.337+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.343+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 134: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.344+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.356+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 135: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.357+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.364+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 136: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.368+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.373+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 137: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.375+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.383+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 138: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.384+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.406+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 139: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.409+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.418+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 140: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.420+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.426+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 141: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.427+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.433+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 142: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.435+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.440+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 143: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.441+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.449+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 144: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.450+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.460+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 145: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.466+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.485+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 146: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.486+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.501+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 147: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.507+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.520+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 148: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.521+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.527+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 149: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.528+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.535+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 150: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.537+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.548+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 151: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.549+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.569+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 152: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.571+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.600+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 153: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.607+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.621+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 154: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.622+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.629+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 155: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.630+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.635+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 156: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.637+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.646+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 157: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.648+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.657+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 158: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.664+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.679+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 159: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.684+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.699+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 160: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.705+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.712+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 161: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.716+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.724+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 162: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.725+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.734+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 163: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.736+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.743+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 164: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.745+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.756+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 165: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.758+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.768+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 166: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.772+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.792+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 167: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.797+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.807+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 168: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.810+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.819+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 169: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.820+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.831+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 170: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.832+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.841+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 171: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.844+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.855+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 172: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.857+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.875+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 173: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.876+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.900+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 174: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.904+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.920+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 175: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.921+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.938+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 176: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.940+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.951+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 177: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.953+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.967+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 178: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.970+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:16.986+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 179: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:16.994+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.013+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 180: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.015+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.030+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 181: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.034+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.049+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 182: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.053+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.072+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 183: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.077+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.092+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 184: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.099+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.115+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 185: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.118+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.126+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 186: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.130+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.154+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 187: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.158+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.174+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 188: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.181+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.198+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 189: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.201+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.209+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 190: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.210+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.224+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 191: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.225+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.238+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 192: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.245+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.259+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 193: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.267+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.282+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 194: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.296+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.313+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 195: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.319+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.342+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 196: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.345+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.367+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 197: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.369+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.387+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 198: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.392+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.417+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 199: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.421+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.438+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 200: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.440+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.467+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 201: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.479+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.540+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 202: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.554+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.589+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 203: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.600+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:04:17.648+0000] {process_and_clean_data.py:519} ERROR - Error al insertar lote 204: (1265, "Data truncated for column '0' at row 1")
[2025-05-03T07:04:17.649+0000] {process_and_clean_data.py:527} WARNING - ‚ö† Datos guardados parcialmente en diabetes_validation_processed:
[2025-05-03T07:04:17.649+0000] {process_and_clean_data.py:528} WARNING -    - Filas insertadas: 0 de 20353
[2025-05-03T07:04:17.891+0000] {python.py:237} INFO - Done. Returned value was: 0
[2025-05-03T07:04:17.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T07:04:18.122+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=diabetes_data_pipeline, task_id=save_validation_data, execution_date=20250503T070247, start_date=20250503T070406, end_date=20250503T070418
[2025-05-03T07:04:18.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-03T07:04:18.493+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T07:04:18.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
