[2025-04-08T00:06:12.424+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T00:06:12.466+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-08T00:06:07.426650+00:00 [queued]>
[2025-04-08T00:06:12.482+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-08T00:06:07.426650+00:00 [queued]>
[2025-04-08T00:06:12.482+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-08T00:06:12.513+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2025-04-08 00:06:07.426650+00:00
[2025-04-08T00:06:12.534+0000] {standard_task_runner.py:63} INFO - Started process 59262 to run task
[2025-04-08T00:06:12.544+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clean_transform_data', 'transform_data', 'manual__2025-04-08T00:06:07.426650+00:00', '--job-id', '685', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpjpvb0a3_']
[2025-04-08T00:06:12.551+0000] {standard_task_runner.py:91} INFO - Job 685: Subtask transform_data
[2025-04-08T00:06:12.638+0000] {task_command.py:426} INFO - Running <TaskInstance: clean_transform_data.transform_data manual__2025-04-08T00:06:07.426650+00:00 [running]> on host 1e5dd8b23497
[2025-04-08T00:06:12.784+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_transform_data' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:06:07.426650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T00:06:07.426650+00:00'
[2025-04-08T00:06:12.786+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T00:06:12.820+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-08T00:06:12.830+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-08T00:06:12.877+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-04-08T00:06:19.500+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T00:06:19.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T00:06:19.517+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clean_transform_data, task_id=transform_data, execution_date=20250408T000607, start_date=20250408T000612, end_date=20250408T000619
[2025-04-08T00:06:19.642+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T00:06:19.675+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T00:06:19.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
