[2025-05-03T07:09:10.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T07:09:10.664+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_diabetes_processed_tables.validate_train_data manual__2025-05-03T07:08:58.037317+00:00 [queued]>
[2025-05-03T07:09:10.725+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_diabetes_processed_tables.validate_train_data manual__2025-05-03T07:08:58.037317+00:00 [queued]>
[2025-05-03T07:09:10.729+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T07:09:10.855+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): validate_train_data> on 2025-05-03 07:08:58.037317+00:00
[2025-05-03T07:09:10.928+0000] {standard_task_runner.py:63} INFO - Started process 832 to run task
[2025-05-03T07:09:10.993+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'validate_diabetes_processed_tables', 'validate_train_data', 'manual__2025-05-03T07:08:58.037317+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/validation_processed_data.py', '--cfg-path', '/tmp/tmp4uim7dly']
[2025-05-03T07:09:11.074+0000] {standard_task_runner.py:91} INFO - Job 211: Subtask validate_train_data
[2025-05-03T07:09:11.546+0000] {task_command.py:426} INFO - Running <TaskInstance: validate_diabetes_processed_tables.validate_train_data manual__2025-05-03T07:08:58.037317+00:00 [running]> on host e89618938543
[2025-05-03T07:09:12.313+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_diabetes_processed_tables' AIRFLOW_CTX_TASK_ID='validate_train_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T07:08:58.037317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T07:08:58.037317+00:00'
[2025-05-03T07:09:12.315+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T07:09:12.460+0000] {validation_processed_data.py:47} INFO - Iniciando validaci�n de tabla diabetes_train_processed...
[2025-05-03T07:09:12.464+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-03T07:09:12.471+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-03T07:09:12.480+0000] {sql.py:457} INFO - Running statement: 
        SELECT COUNT(*) as count 
        FROM information_schema.tables 
        WHERE table_schema = DATABASE() 
        AND table_name = 'diabetes_train_processed'
        , parameters: None
[2025-05-03T07:09:12.488+0000] {sql.py:466} INFO - Rows affected: 1
[2025-05-03T07:09:12.492+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:407: AirflowProviderDeprecationWarning: Call to deprecated method _make_common_data_structure. (The `_make_serializable` method is deprecated and support will be removed in a future version of the common.sql provider. Please update the DbApiHook's provider to a version based on common.sql >= 1.9.1.)
  result = self._make_common_data_structure(handler(cur))

[2025-05-03T07:09:12.498+0000] {validation_processed_data.py:196} ERROR - L Error durante la validaci�n de diabetes_train_processed: tuple indices must be integers or slices, not str
[2025-05-03T07:09:12.598+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T07:09:12.599+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/validation_processed_data.py", line 64, in validate_processed_table
    table_exists = result[0]['count'] > 0
TypeError: tuple indices must be integers or slices, not str
[2025-05-03T07:09:12.670+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=validate_diabetes_processed_tables, task_id=validate_train_data, execution_date=20250503T070858, start_date=20250503T070910, end_date=20250503T070912
[2025-05-03T07:09:12.734+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 211 for task validate_train_data (tuple indices must be integers or slices, not str; 832)
[2025-05-03T07:09:12.818+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T07:09:12.934+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T07:09:12.937+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
