[2025-04-20T00:06:10.511+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-20T00:06:10.542+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-20T00:06:06.494053+00:00 [queued]>
[2025-04-20T00:06:10.558+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_transform_data.transform_data manual__2025-04-20T00:06:06.494053+00:00 [queued]>
[2025-04-20T00:06:10.558+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-20T00:06:10.585+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2025-04-20 00:06:06.494053+00:00
[2025-04-20T00:06:10.611+0000] {standard_task_runner.py:63} INFO - Started process 214525 to run task
[2025-04-20T00:06:10.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clean_transform_data', 'transform_data', 'manual__2025-04-20T00:06:06.494053+00:00', '--job-id', '759', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_data.py', '--cfg-path', '/tmp/tmpkeulkoq5']
[2025-04-20T00:06:10.626+0000] {standard_task_runner.py:91} INFO - Job 759: Subtask transform_data
[2025-04-20T00:06:10.707+0000] {task_command.py:426} INFO - Running <TaskInstance: clean_transform_data.transform_data manual__2025-04-20T00:06:06.494053+00:00 [running]> on host e1dfa1bb16b8
[2025-04-20T00:06:10.840+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_transform_data' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T00:06:06.494053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T00:06:06.494053+00:00'
[2025-04-20T00:06:10.842+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-20T00:06:10.876+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-20T00:06:10.886+0000] {base.py:84} INFO - Using connection ID 'mysql_***_conn' for task execution.
[2025-04-20T00:06:10.923+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-04-20T00:06:17.863+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-20T00:06:17.866+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-20T00:06:17.890+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clean_transform_data, task_id=transform_data, execution_date=20250420T000606, start_date=20250420T000610, end_date=20250420T000617
[2025-04-20T00:06:17.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-20T00:06:18.010+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T00:06:18.012+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
