[2025-05-01T05:24:10.252+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T05:24:10.317+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:23:47.993718+00:00 [queued]>
[2025-05-01T05:24:10.353+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:23:47.993718+00:00 [queued]>
[2025-05-01T05:24:10.357+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-05-01T05:24:10.468+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_validation_data.process_validation_batches> on 2025-05-01 05:23:47.993718+00:00
[2025-05-01T05:24:10.498+0000] {standard_task_runner.py:63} INFO - Started process 269 to run task
[2025-05-01T05:24:10.514+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_diabetes_data', 'process_validation_data.process_validation_batches', 'manual__2025-05-01T05:23:47.993718+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_store_data.py', '--cfg-path', '/tmp/tmpf94k39bk']
[2025-05-01T05:24:10.529+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask process_validation_data.process_validation_batches
[2025-05-01T05:24:10.721+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:23:47.993718+00:00 [running]> on host 8fe9b8e6dafd
[2025-05-01T05:24:11.046+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_diabetes_data' AIRFLOW_CTX_TASK_ID='process_validation_data.process_validation_batches' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T05:23:47.993718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T05:23:47.993718+00:00'
[2025-05-01T05:24:11.048+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T05:24:11.140+0000] {fetch_and_store_data.py:189} INFO - Procesando 2 batches para validation
[2025-05-01T05:24:11.141+0000] {fetch_and_store_data.py:117} INFO - Obteniendo validation batch 0 desde http://datapi:80/get-validation-batch/?batch_number=0
[2025-05-01T05:24:29.849+0000] {fetch_and_store_data.py:129} INFO - Obtenidos 15000 registros de validation batch 0
[2025-05-01T05:24:29.858+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-01T05:24:29.864+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-01T05:24:31.194+0000] {fetch_and_store_data.py:173} ERROR - Error procesando validation batch 0: '<' not supported between instances of 'NoneType' and 'str'
[2025-05-01T05:24:31.195+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T05:24:31.196+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_store_data.py", line 193, in process_dataset
    records_inserted = fetch_and_store_batch(
  File "/opt/airflow/dags/fetch_and_store_data.py", line 167, in fetch_and_store_batch
    connection.execute(text(sql), values)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1553, in _execute_clauseelement
    keys = sorted(distilled_params[0])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
[2025-05-01T05:24:31.264+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_diabetes_data, task_id=process_validation_data.process_validation_batches, execution_date=20250501T052347, start_date=20250501T052410, end_date=20250501T052431
[2025-05-01T05:24:31.343+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task process_validation_data.process_validation_batches ('<' not supported between instances of 'NoneType' and 'str'; 269)
[2025-05-01T05:24:31.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-01T05:24:31.520+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T05:24:31.524+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
